print("Opened Song.spec.lua")
return function()
    print("Running Song.spec.lua")
    local SongData = require(script.Parent.SongData)
    local Base64 = require(script.Parent.Base64)
    local Song = require(script.Parent.Song)
    local midiData = Base64.decode(SongData.StairwayToHeaven)
    local song = Song.new(midiData)
    describe("Should be the right song data", function()
        it("Should step through the song accordingly!", function()
            expect(math.round(song.TimeLength)).to.equal(331)
            local events = song:GetNoteEvents()
            expect(events[1].noteToPlay).to.equal(69)
        end)
    end)
end